source 'https://rubygems.org'

gem 'bundler', '~> 1.0'
gem 'rake', '~> 12.0'

gem 'hiredis', '~> 0.6.0', require: false
gem 'ohm', '~> 3.0'
gem 'sequel', '~> 5.0', require: false
gem 'mysql2', '~> 0.4', require: false

gem 'uuid64'
# gem 'em-midori', require: 'midori', :path => '/Users/delton/WorkSpace/Midori/midori'
gem 'midori.rb', '~> 0.4.3'
gem 'midori-contrib', '~> 0.1.0', require: %w(
    midori-contrib
    midori-contrib/file
    midori-contrib/sequel/mysql2
    midori-contrib/redic
  )
